### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#14]
1. When we login we fill username and password...but wen we give any wrong password or wrong username.  
   it doesn't warn any message lyk "wrong password" or "wrong username". it can't login but a warning message must  come..

![login](https://f.cloud.github.com/assets/2959939/1513661/311a47d4-4ae6-11e3-817c-e5455f530b99.png)

**Comment by TheItachiUchiha** [comment]
message should be "Incorrect Username or Password"

**Comment by birajawithu** [comment]
Fixed

**Comment by dhalchittaranjan** [comment]
Fixed and Closed.
