### ISSUE TITLE
User:Modify User

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#16]
1.. Here user Modify the Mobile no take less than 10 digit and its save easily..
2.  Mobile no should be 10 digit..

![user modify](https://f.cloud.github.com/assets/2959939/1524877/c63a5c32-4bcc-11e3-943e-80ad0cef4e7b.png)

**Comment by TheItachiUchiha** [comment]
Why are you closing the issues assigned to chittaranjan ?
