### ISSUE TITLE
USER

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#17]
1.. In Mobile less than 10 digit accept and added user easily without showing any error message...

![create user](https://f.cloud.github.com/assets/2959939/1534315/52ca9fce-4c93-11e3-8aec-b5b95bc7f834.png)

**Comment by birajawithu** [comment]
Fixed n Checked In

**Comment by dhalchittaranjan** [comment]
Fix and Varified..
