### ISSUE TITLE
Customer

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#33]
1. I hv taken one screenshot of Customer but every field lyk Customer,User,Component have same problem.

2.. In create or modify field if we give wrong data and Save it shows some msg i.e  give correct input orelse but wen 2nd tym we give correct data to it and save it ,  it saved but dat color must green rather red..

![customer](https://f.cloud.github.com/assets/2959939/1584866/5933112c-5213-11e3-81ec-334d186412ed.png)
 it and save it ,  it saved but dat color luks red.

**Comment by birajawithu** [comment]
This is already taken as a Issue ..#30
