### ISSUE TITLE
Components : View Components

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#34]
1. In Documents it is given Component Name not Name.. Correct it.

![compnts](https://f.cloud.github.com/assets/2959939/1584970/cc805ecc-5214-11e3-86e5-aa631414b5ad.png)

**Comment by birajawithu** [comment]
This is not an Issue.. u only have 2 change the table column Name

**Comment by dhalchittaranjan** [comment]
Fixed ....
