### ISSUE TITLE
product_view

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#35]
![product_view](https://f.cloud.github.com/assets/2959939/1631789/ff07ba4a-576c-11e3-9b3a-b8a4549d8d26.png)
1. u should add  Export  in Action Field as per doc.

**Comment by birajawithu** [comment]
Ok i'll fix it Soon.

**Comment by dhalchittaranjan** [comment]
Fix it den rply!!
