### ISSUE TITLE
Component View

### ISSUE THREAD

**Issue by birajawithu** [TheItachiUchiha/QuotationFX#38]
when we select product Category all the product category are shown in AutoFillTextField but when we try to select any other Option From Combo, the AutofillTextField does not reflect rather its shows the same product Categories

here are two Snaps Taken...
![capture2](https://f.cloud.github.com/assets/5780328/1648660/fc7047e4-59af-11e3-955e-4d72b6d02658.png)
![capture1](https://f.cloud.github.com/assets/5780328/1648661/040b292e-59b0-11e3-9959-dd1caf082384.png)
![capture1](https://f.cloud.github.com/assets/5780328/1648662/062eeaf6-59b0-11e3-8aa9-9b8a09229f9f.png)

**Comment by TheItachiUchiha** [comment]
Fixed

**Comment by birajawithu** [comment]
Thank u
