### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#39]
1. TIN Number and Email Id doesn't work auto field.
2. Wen we fill Tin No and press tab 2 times it jumps to Customer Name directly rather jump to next line.
3. In contact number required Validation.
4. If a customer give same  either  TIN No or Email Id then other fields should come automatically rather fill again same thing. 

![enqry](https://f.cloud.github.com/assets/2959939/1648794/b2a4328a-59c1-11e3-8317-6962d84e065d.png)

**Comment by birajawithu** [comment]
fixed issue#39
get the latest n check it again..
