### ISSUE TITLE
User:Modify User

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#4]
Here user should be given modify multiple time if user modify some field and forgot to modify any other field at same time ... when user modify second time in same page so it should be shown another message rather same existing message 'User Modified' ...
then user can ensure that the field modify or not..

![modify user](https://f.cloud.github.com/assets/2959939/1500633/d608600e-487b-11e3-9e21-b7617b9ce090.png)

**Comment by TheItachiUchiha** [comment]
Pull the latest Update n Check it Again

**Comment by dhalchittaranjan** [comment]
Fixed And Closed..
