### ISSUE TITLE
Products are getting saved without Components

### ISSUE THREAD

**Issue by TheItachiUchiha** [TheItachiUchiha/QuotationFX#51]
Atleast one component is mandatory to save any product

**Comment by birajawithu** [comment]
it will Show you a Message "No Product Component(s) Added " instead of saving product Details, if u want to save a product Without any Component.....
Plz Check once Again

**Comment by TheItachiUchiha** [comment]
in modify, no validation is added

**Comment by TheItachiUchiha** [comment]
closed
