### ISSUE TITLE
Error during loading css

### ISSUE THREAD

**Issue by TheItachiUchiha** [TheItachiUchiha/QuotationFX#62]
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-background-color' while resolving lookups for '-fx-text-fill' from rule '_.label' in stylesheet jar:file:/C:/Program%20Files/Java/jdk1.7.0_09/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '_.menu-button' in stylesheet jar:file:/C:/Program%20Files/Java/jdk1.7.0_09/jre/lib/jfxrt.jar!/com/sun/javafx/scene/control/skin/caspian/caspian.bss
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '_.button' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '_.toggle-button' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '_.toggle-button' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '_.toggle-button' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-light-text-color' while resolving lookups for '-fx-text-fill' from rule '_.toggle-button:selected' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-light-text-color' while resolving lookups for '-fx-text-fill' from rule '_.toggle-button:selected' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css
WARNING: com.sun.javafx.css.StyleHelper calculateValue Could not resolve '-fx-light-text-color' while resolving lookups for '-fx-text-fill' from rule '*.toggle-button:selected' in stylesheet file:/C:/Users/HOME/git/QuotationFX/Quotations/bin/com/kc/style/gui.css

**Comment by birajawithu** [comment]
Fixed
