### ISSUE TITLE
Home:Logout

### ISSUE THREAD

**Issue by dhalchittaranjan** [TheItachiUchiha/QuotationFX#7]
1. Wen the page is normal the logout shows in middle .
2. Wen the page is minimize it shows in exact place i.e. the right corner.
3. The logout button must show in right corner as normal or minimize case.

![home logout](https://f.cloud.github.com/assets/2959939/1502861/5bb4d780-48a1-11e3-907e-0074cf44e469.png)

**Comment by birajawithu** [comment]
Fixed
